### ISSUE TITLE
FindByEmailAsync always return null

### ISSUE THREAD

**Issue by sergey-messer** [matteofabbri/AspNetCore.Identity.Mongo#26] opened 2019-10-05 15:41 UTC
FindByEmailAsync always return null
The bug is in UserStore.cs:
```
public async Task<TUser> FindByEmailAsync(string normalizedEmail, CancellationToken cancellationToken)
{
   cancellationToken.ThrowIfCancellationRequested();
   return await ById(normalizedEmail);
}

```
Using ById(normalizedEmail) function is wrong

In preview version was:

```
public async Task<TUser> FindByEmailAsync(string normalizedEmail, CancellationToken cancellationToken)
{
    cancellationToken.ThrowIfCancellationRequested();
    return await _userCollection.FindByEmailAsync(normalizedEmail);
}

```

**Comment by matteofabbri** [comment] 2019-10-29 09:32
Thanks a lot :) fixed in https://github.com/matteofabbri/AspNetCore.Identity.Mongo/pull/27

**Closed by matteofabbri** 2019-10-29 09:32 UTC

**Comment by mcbaloo** [comment] 2020-12-18 10:49
I am trying to save user record but I also noticed that NormalizedEmail is null in my MongoCollection after saving the record. What could be the cause?
